[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[workspace.dependencies]
# local crates

