[book]
authors = ["RenYan Wei"]
language = "en"
multilingual = false
src = "src"
title = "Hello Rust"


[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
# 指定输出目录为 docs
default-theme = "light"
#root = "/hello-rust/"
git-repository-url = "https://github.com/savechina/hello-rust"
git-repository-icon = "fa-github"
additional-css = ["./mdbook-admonish.css"]
