name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # 2. 安装 protoc
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "29.3"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
